apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: garin94@live.co.uk
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        azureDNS:
          clientID: 238c535b-cd54-490a-a040-d227d178bebd
          clientSecretSecretRef:
            name: azuredns-config
            key: client-secret
          subscriptionID: 542a0e08-b7f3-4936-9509-d1b7f503ef73
          tenantID: 3f2aff0e-933a-4598-84b5-0ceb168b440e
          resourceGroupName: ghdev-rg
          hostedZoneName: ghdev.uk
          environment: AzurePublicCloud

# kubectl create secret generic azuredns-config --from-literal=client-secret=<YOUR_CLIENT_SECRET> --namespace=cert-manager