apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ghdev-uk-tls
  namespace: ics
spec:
  secretName: ghdev-uk-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ghdev.uk
  dnsNames:
    - ghdev.uk
    - www.ghdev.uk